id: P006845
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W23223
  title: བསྡུས་གཞུང་རིག་པ་མི་ཟད་པའི་གཏེར་མཛོད་འདོ་འཇོའི་བ་མོ
  author: ''
  volumes:
    9aee40ffff78493a9caad0c82653e153:
      image_group_id: I0860
      title: ''
      volume_number: 1
      total_pages: 230
      base_file: v001.txt
